version: "3"

vars:
  AWS_REGION: ap-northeast-1
  LOCALSTACK_ENDPOINT: localhost:4566
  SONARQUBE_ENDPOINT: localhost:9000

dotenv: ["Taskfile.sonar.env"]


includes:
  local:
    taskfile: ./api/taskfile.local.yml
    dir: ./api

  cloud:
    taskfile: ./api/taskfile.cloud.yml
    dir: ./api
  
  testreport:
    taskfile: ./taskfile.testreport.yml
    dir: .

tasks:
  local-up:
    cmds:
      - task: local:local-up
    desc: "[local] 建立本地開發環境"

  local-down:
    cmds:
      - task: local:local-down
    desc: "[local] 移除本地開發環境"

  cloud-up:
    cmds:
      - task: cloud:cloud-up
    desc: "[cloud] 建立雲端環境"

  cloud-down:
    cmds:
      - task: cloud:cloud-down
    desc: "[cloud] 刪除雲端環境"

  test-platform-init:
    cmds:
        - task: testreport:sonarqube-up
    desc : "[test] 產生測試平台-soanrqube"

  test-report-create:
    cmds:
        - task: testreport:sonarscan-all 
    desc : "[test] 產生測試報告"
  